### PR TITLE
Automatic configuration of proxy routers using the Coordinator app

### PR DESCRIPTION
**Pull request by agneum**
- register/unregister proxy routers 
- update proto files and open ports to run coordinator
- configure a new proxy router using coordinator
- store ShardingRules and apply the existing rules to the router after registration
- implement the ShardingRules service in proxy routers

### CODE REVIEW

**Comment by agneum** [comment]
### Example
**Configure sharding**
```
db1=> create sharding column id;
 coordinator 
-------------
 query ok
(1 row)

db1=> add key range 1 1000 sh1 krid1;
 coordinator 
-------------
 query ok
(1 row)

db1=> add key range 1001 2000 sh2 krid2;
 coordinator 
-------------
 query ok
(1 row)

```
**Restart the proxy router**

```
$ docker-compose restart router

$ grpcurl -plaintext '192.168.233.04:7000'  yandex.spqr.KeyRangeService/ListKeyRange
{
  
}

$ grpcurl -plaintext '192.168.233.04:7000'  yandex.spqr.ShardingRulesService/ListShardingRules
{
  
}
```
**Register the restarted router**
```
db1=?> register router spqr_router_1_1:7000 r0;
 coordinator 
-------------
 query ok
(1 row)
```

**Check the router configuration**
```
$ grpcurl -plaintext '192.168.233.04:7000'  yandex.spqr.KeyRangeService/ListKeyRange
{
  "keyRangesInfo": [
    {
      "keyRange": {
        "lowerBound": "1",
        "upperBound": "1000"
      },
      "krid": "krid1",
      "shardId": "sh1"
    },
    {
      "keyRange": {
        "lowerBound": "1001",
        "upperBound": "2000"
      },
      "krid": "krid2",
      "shardId": "sh2"
    }
  ]
}

$ grpcurl -plaintext '192.168.233.04:7000'  yandex.spqr.ShardingRulesService/ListShardingRules
{
  "rules": [
    {
      "columns": [
        "id"
      ]
    }
  ]
}
```

**Review by x4m — APPROVED** [review]

**Comment by reshke** [comment]
Can we rebase this on master to make this mergeable?
changes seems ok, i can also try to rebase it myself in my free-time

**Comment by gedw99** [comment]
This looks really cool.

If the routing / sharding rules are stored this way, then the Proxy can use them at runtime to work out where to run the select queries on ?

**Comment by Denchick** [comment]
It is a pity we did not find the time and effort to review and merge this PR. Come back with new prs, we won't let you down

**Pull request closed without merging**
