### PR TITLE
Balancer App

### PR DESCRIPTION
**Pull request by agneum**
- implement the Shard service
- run balancer: register shards, init the metadata DB, dockerize balancer
- list key ranges to use in the balancer
- fix balancer db connections and queries to manage actions
- fix key range lock, data transfer, key range move, delete old key range
- implement key ranges uniting
- add sharding key to the config, rewrite installation queries by removing hardcoded table values
- make possible to run parallel tasks and fix data duplication on move a table

### CODE REVIEW

**Comment by NikolayS** [comment]
@x4m should we rename it before this gets merged? "Resharder" and "Mover" were the two good options so far.

**Comment by agneum** [comment]
@reshke @munakoiso @x4m Please review

Do you have any suggestions?

**Review by reshke — APPROVED** [review]
plz rebase

**Comment by agneum** [comment]
> plz rebase

@reshke I suggest squashing and merging the PR because it's almost impossible to resolve all conflicts during rebasing

**Comment by reshke** [comment]
Ok

**Pull request merged**
